/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBusinessRouteImport } from './routes/admin/business'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminGovernmentRouteImport } from './routes/admin/government'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppRulesRouteImport } from './routes/app/rules'
import { Route as AppScanRouteImport } from './routes/app/scan'
import { Route as AuthCompanyRouteImport } from './routes/auth.company'
import { Route as AuthGovernmentRouteImport } from './routes/auth.government'
import { Route as AppInspectionsIndexRouteImport } from './routes/app/inspections/index'
import { Route as AppInspectionsInspectionIdRouteImport } from './routes/app/inspections/$inspectionId'
import { Route as AppReviewsIndexRouteImport } from './routes/app/reviews/index'
import { Route as AppReviewsReviewIdRouteImport } from './routes/app/reviews/$reviewId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessRoute = AdminBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGovernmentRoute = AdminGovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AuthCompanyRoute = AuthCompanyRouteImport.update({
  id: '/auth/company',
  path: '/auth/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGovernmentRoute = AuthGovernmentRouteImport.update({
  id: '/auth/government',
  path: '/auth/government',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInspectionsIndexRoute = AppInspectionsIndexRouteImport.update({
  id: '/inspections/',
  path: '/inspections/',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsInspectionIdRoute =
  AppInspectionsInspectionIdRouteImport.update({
    id: '/inspections/$inspectionId',
    path: '/inspections/$inspectionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppReviewsIndexRoute = AppReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsReviewIdRoute = AppReviewsReviewIdRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/government': typeof AdminGovernmentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/rules': typeof AppRulesRoute
  '/app/scan': typeof AppScanRoute
  '/auth/company': typeof AuthCompanyRoute
  '/auth/government': typeof AuthGovernmentRoute
  '/admin/': typeof AdminIndexRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/reviews/$reviewId': typeof AppReviewsReviewIdRoute
  '/app/inspections/': typeof AppInspectionsIndexRoute
  '/app/reviews/': typeof AppReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/government': typeof AdminGovernmentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/rules': typeof AppRulesRoute
  '/app/scan': typeof AppScanRoute
  '/auth/company': typeof AuthCompanyRoute
  '/auth/government': typeof AuthGovernmentRoute
  '/admin': typeof AdminIndexRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/reviews/$reviewId': typeof AppReviewsReviewIdRoute
  '/app/inspections': typeof AppInspectionsIndexRoute
  '/app/reviews': typeof AppReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/government': typeof AdminGovernmentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/rules': typeof AppRulesRoute
  '/app/scan': typeof AppScanRoute
  '/auth/company': typeof AuthCompanyRoute
  '/auth/government': typeof AuthGovernmentRoute
  '/admin/': typeof AdminIndexRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/reviews/$reviewId': typeof AppReviewsReviewIdRoute
  '/app/inspections/': typeof AppInspectionsIndexRoute
  '/app/reviews/': typeof AppReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/reset-password'
    | '/admin/business'
    | '/admin/dashboard'
    | '/admin/government'
    | '/admin/login'
    | '/admin/overview'
    | '/admin/users'
    | '/app/dashboard'
    | '/app/rules'
    | '/app/scan'
    | '/auth/company'
    | '/auth/government'
    | '/admin/'
    | '/app/inspections/$inspectionId'
    | '/app/reviews/$reviewId'
    | '/app/inspections/'
    | '/app/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/reset-password'
    | '/admin/business'
    | '/admin/dashboard'
    | '/admin/government'
    | '/admin/login'
    | '/admin/overview'
    | '/admin/users'
    | '/app/dashboard'
    | '/app/rules'
    | '/app/scan'
    | '/auth/company'
    | '/auth/government'
    | '/admin'
    | '/app/inspections/$inspectionId'
    | '/app/reviews/$reviewId'
    | '/app/inspections'
    | '/app/reviews'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/reset-password'
    | '/admin/business'
    | '/admin/dashboard'
    | '/admin/government'
    | '/admin/login'
    | '/admin/overview'
    | '/admin/users'
    | '/app/dashboard'
    | '/app/rules'
    | '/app/scan'
    | '/auth/company'
    | '/auth/government'
    | '/admin/'
    | '/app/inspections/$inspectionId'
    | '/app/reviews/$reviewId'
    | '/app/inspections/'
    | '/app/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCompanyRoute: typeof AuthCompanyRoute
  AuthGovernmentRoute: typeof AuthGovernmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business': {
      id: '/admin/business'
      path: '/business'
      fullPath: '/admin/business'
      preLoaderRoute: typeof AdminBusinessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/government': {
      id: '/admin/government'
      path: '/government'
      fullPath: '/admin/government'
      preLoaderRoute: typeof AdminGovernmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rules': {
      id: '/app/rules'
      path: '/rules'
      fullPath: '/app/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/company': {
      id: '/auth/company'
      path: '/auth/company'
      fullPath: '/auth/company'
      preLoaderRoute: typeof AuthCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/government': {
      id: '/auth/government'
      path: '/auth/government'
      fullPath: '/auth/government'
      preLoaderRoute: typeof AuthGovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inspections/': {
      id: '/app/inspections/'
      path: '/inspections'
      fullPath: '/app/inspections/'
      preLoaderRoute: typeof AppInspectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inspections/$inspectionId': {
      id: '/app/inspections/$inspectionId'
      path: '/inspections/$inspectionId'
      fullPath: '/app/inspections/$inspectionId'
      preLoaderRoute: typeof AppInspectionsInspectionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews/': {
      id: '/app/reviews/'
      path: '/reviews'
      fullPath: '/app/reviews/'
      preLoaderRoute: typeof AppReviewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews/$reviewId': {
      id: '/app/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/app/reviews/$reviewId'
      preLoaderRoute: typeof AppReviewsReviewIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBusinessRoute: typeof AdminBusinessRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGovernmentRoute: typeof AdminGovernmentRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBusinessRoute: AdminBusinessRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGovernmentRoute: AdminGovernmentRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppRulesRoute: typeof AppRulesRoute
  AppScanRoute: typeof AppScanRoute
  AppInspectionsInspectionIdRoute: typeof AppInspectionsInspectionIdRoute
  AppReviewsReviewIdRoute: typeof AppReviewsReviewIdRoute
  AppInspectionsIndexRoute: typeof AppInspectionsIndexRoute
  AppReviewsIndexRoute: typeof AppReviewsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppRulesRoute: AppRulesRoute,
  AppScanRoute: AppScanRoute,
  AppInspectionsInspectionIdRoute: AppInspectionsInspectionIdRoute,
  AppReviewsReviewIdRoute: AppReviewsReviewIdRoute,
  AppInspectionsIndexRoute: AppInspectionsIndexRoute,
  AppReviewsIndexRoute: AppReviewsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCompanyRoute: AuthCompanyRoute,
  AuthGovernmentRoute: AuthGovernmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
